server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel-package-db?useSSL=false&serverTimezone=UTC
    username: root
    password: mystrongpassword2023
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect